use assert_cmd::Command;
use serde_json::json;
use std::fs;
use tempfile::TempDir;

#[test]
fn remove_mcp_tool() {
    let project_dir = TempDir::new().unwrap();
    let packages_dir = TempDir::new().unwrap();

    // Write claude-env.toml with two MCP tools.
    fs::write(
        project_dir.path().join("claude-env.toml"),
        "[mcp]\ncontext7 = \"latest\"\nchrome-devtools = \"latest\"\n",
    )
    .unwrap();

    // Write .mcp.json with both tools.
    let mcp_json = json!({
        "mcpServers": {
            "context7": {
                "type": "stdio",
                "command": "npx",
                "args": ["-y", "@upstash/context7-mcp@latest"]
            },
            "chrome-devtools": {
                "type": "stdio",
                "command": "npx",
                "args": ["-y", "chrome-devtools-mcp@latest"]
            }
        }
    });
    fs::write(
        project_dir.path().join(".mcp.json"),
        serde_json::to_string_pretty(&mcp_json).unwrap(),
    )
    .unwrap();

    // Create package dir for context7 (simulates installed state).
    let context7_dir = packages_dir.path().join("context7");
    fs::create_dir_all(&context7_dir).unwrap();

    // Write lockfile with both tools.
    fs::write(
        project_dir.path().join("claude-env.lock"),
        "# Auto-generated by claude-env. Do not edit.\n\n\
        [mcp.chrome-devtools]\nversion = \"1.0.0\"\n\n\
        [mcp.context7]\nversion = \"2.1.4\"\n",
    )
    .unwrap();

    // Run `claude-env remove context7`.
    let mut cmd = Command::cargo_bin("claude-env").unwrap();
    cmd.arg("remove")
        .arg("context7")
        .current_dir(project_dir.path())
        .env("CLAUDE_ENV_HOME", packages_dir.path());

    cmd.assert().success();

    // Assert: claude-env.toml no longer contains context7 but still has chrome-devtools.
    let toml_content = fs::read_to_string(project_dir.path().join("claude-env.toml")).unwrap();
    assert!(
        !toml_content.contains("context7"),
        "claude-env.toml should not contain context7, got:\n{toml_content}"
    );
    assert!(
        toml_content.contains("chrome-devtools"),
        "claude-env.toml should still contain chrome-devtools, got:\n{toml_content}"
    );

    // Assert: .mcp.json no longer contains context7 entry.
    let mcp_content = fs::read_to_string(project_dir.path().join(".mcp.json")).unwrap();
    let mcp_value: serde_json::Value = serde_json::from_str(&mcp_content).unwrap();
    assert!(
        mcp_value["mcpServers"].get("context7").is_none(),
        ".mcp.json should not contain context7, got:\n{mcp_content}"
    );
    assert!(
        mcp_value["mcpServers"].get("chrome-devtools").is_some(),
        ".mcp.json should still contain chrome-devtools, got:\n{mcp_content}"
    );

    // Assert: package directory for context7 was removed.
    assert!(
        !context7_dir.exists(),
        "package dir for context7 should have been removed"
    );

    // Assert: lockfile no longer contains context7.
    let lock_content = fs::read_to_string(project_dir.path().join("claude-env.lock")).unwrap();
    assert!(
        !lock_content.contains("context7"),
        "lockfile should not contain context7, got:\n{lock_content}"
    );
    assert!(
        lock_content.contains("chrome-devtools"),
        "lockfile should still contain chrome-devtools, got:\n{lock_content}"
    );
}

#[test]
fn remove_nonexistent_tool_exits_with_error() {
    let project_dir = TempDir::new().unwrap();
    let packages_dir = TempDir::new().unwrap();

    // Write a config without the tool we're trying to remove.
    fs::write(
        project_dir.path().join("claude-env.toml"),
        "[mcp]\ncontext7 = \"latest\"\n",
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("claude-env").unwrap();
    cmd.arg("remove")
        .arg("nonexistent-tool")
        .current_dir(project_dir.path())
        .env("CLAUDE_ENV_HOME", packages_dir.path());

    cmd.assert().failure();
}
