use claude_env::lockfile::{LockedTool, Lockfile};

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

#[test]
fn parse_lockfile() {
    let toml = r#"
[mcp]
context7 = { version = "1.2.3", package = "@upstash/context7-mcp", integrity = "sha512-abc", resolved_at = "2026-04-20T00:00:00Z" }
memory = { version = "0.5.0" }

[skills]
my-skill = { version = "latest", package = "skills.sh/owner/repo/my-skill" }
"#;

    let lock = Lockfile::parse(toml).unwrap();

    // mcp section
    let ctx7 = lock.get("mcp", "context7").expect("context7 should exist");
    assert_eq!(ctx7.version, "1.2.3");
    assert_eq!(ctx7.package.as_deref(), Some("@upstash/context7-mcp"));
    assert_eq!(ctx7.integrity.as_deref(), Some("sha512-abc"));
    assert_eq!(ctx7.resolved_at.as_deref(), Some("2026-04-20T00:00:00Z"));

    let mem = lock.get("mcp", "memory").expect("memory should exist");
    assert_eq!(mem.version, "0.5.0");
    assert!(mem.package.is_none());
    assert!(mem.integrity.is_none());
    assert!(mem.resolved_at.is_none());

    // skills section
    let skill = lock.get("skills", "my-skill").expect("my-skill should exist");
    assert_eq!(skill.version, "latest");
    assert_eq!(
        skill.package.as_deref(),
        Some("skills.sh/owner/repo/my-skill")
    );
}

// ---------------------------------------------------------------------------
// Roundtrip
// ---------------------------------------------------------------------------

#[test]
fn serialize_lockfile_roundtrip() {
    let mut lock = Lockfile::new();

    lock.set(
        "mcp",
        "context7",
        LockedTool {
            package: Some("@upstash/context7-mcp".to_string()),
            version: "1.2.3".to_string(),
            integrity: Some("sha512-xyz".to_string()),
            resolved_at: Some("2026-04-20T12:00:00Z".to_string()),
        },
    );
    lock.set(
        "skills",
        "my-skill",
        LockedTool {
            package: None,
            version: "latest".to_string(),
            integrity: None,
            resolved_at: None,
        },
    );

    let serialized = lock.serialize();

    // Header must be present
    assert!(serialized.starts_with("# Auto-generated by claude-env. Do not edit.\n\n"));

    // Reparse and verify
    let lock2 = Lockfile::parse(&serialized).unwrap();

    let ctx7 = lock2.get("mcp", "context7").expect("context7 should survive roundtrip");
    assert_eq!(ctx7.version, "1.2.3");
    assert_eq!(ctx7.package.as_deref(), Some("@upstash/context7-mcp"));
    assert_eq!(ctx7.integrity.as_deref(), Some("sha512-xyz"));
    assert_eq!(ctx7.resolved_at.as_deref(), Some("2026-04-20T12:00:00Z"));

    let skill = lock2.get("skills", "my-skill").expect("my-skill should survive roundtrip");
    assert_eq!(skill.version, "latest");
    assert!(skill.package.is_none());
    assert!(skill.integrity.is_none());
    assert!(skill.resolved_at.is_none());
}

// ---------------------------------------------------------------------------
// Empty lockfile
// ---------------------------------------------------------------------------

#[test]
fn empty_lockfile_serializes_with_header_comment() {
    let lock = Lockfile::new();
    assert!(lock.is_empty());

    let serialized = lock.serialize();
    assert!(
        serialized.starts_with("# Auto-generated by claude-env. Do not edit.\n\n"),
        "expected header comment, got: {serialized:?}"
    );
}

// ---------------------------------------------------------------------------
// Missing file
// ---------------------------------------------------------------------------

#[test]
fn lockfile_from_missing_file_returns_empty() {
    let path = std::path::Path::new("/nonexistent/path/claude-env.lock");
    let lock = Lockfile::from_file(path).expect("missing file should return empty lockfile, not error");
    assert!(lock.is_empty());
}
