use assert_cmd::Command;
use serde_json::json;
use std::fs;
use tempfile::TempDir;

#[test]
fn remove_mcp_tool() {
    let project_dir = TempDir::new().unwrap();
    let packages_dir = TempDir::new().unwrap();

    // Write chord.toml with two MCP tools.
    fs::write(
        project_dir.path().join("chord.toml"),
        "[mcp]\ncontext7 = \"latest\"\nchrome-devtools = \"latest\"\n",
    )
    .unwrap();

    // Write .mcp.json with both tools.
    let mcp_json = json!({
        "mcpServers": {
            "context7": {
                "type": "stdio",
                "command": "npx",
                "args": ["-y", "@upstash/context7-mcp@latest"]
            },
            "chrome-devtools": {
                "type": "stdio",
                "command": "npx",
                "args": ["-y", "chrome-devtools-mcp@latest"]
            }
        }
    });
    fs::write(
        project_dir.path().join(".mcp.json"),
        serde_json::to_string_pretty(&mcp_json).unwrap(),
    )
    .unwrap();

    // Create package dir for context7 (simulates installed state).
    let context7_dir = packages_dir.path().join("context7");
    fs::create_dir_all(&context7_dir).unwrap();

    // Write lockfile with both tools.
    fs::write(
        project_dir.path().join("chord.lock"),
        "# Auto-generated by chord. Do not edit.\n\n\
        [mcp.chrome-devtools]\nversion = \"1.0.0\"\n\n\
        [mcp.context7]\nversion = \"2.1.4\"\n",
    )
    .unwrap();

    // Run `chord remove context7`.
    let mut cmd = Command::cargo_bin("chord").unwrap();
    cmd.arg("remove")
        .arg("context7")
        .current_dir(project_dir.path())
        .env("CHORD_HOME", packages_dir.path());

    cmd.assert().success();

    // Assert: chord.toml no longer contains context7 but still has chrome-devtools.
    let toml_content = fs::read_to_string(project_dir.path().join("chord.toml")).unwrap();
    assert!(
        !toml_content.contains("context7"),
        "chord.toml should not contain context7, got:\n{toml_content}"
    );
    assert!(
        toml_content.contains("chrome-devtools"),
        "chord.toml should still contain chrome-devtools, got:\n{toml_content}"
    );

    // Assert: .mcp.json no longer contains context7 entry.
    let mcp_content = fs::read_to_string(project_dir.path().join(".mcp.json")).unwrap();
    let mcp_value: serde_json::Value = serde_json::from_str(&mcp_content).unwrap();
    assert!(
        mcp_value["mcpServers"].get("context7").is_none(),
        ".mcp.json should not contain context7, got:\n{mcp_content}"
    );
    assert!(
        mcp_value["mcpServers"].get("chrome-devtools").is_some(),
        ".mcp.json should still contain chrome-devtools, got:\n{mcp_content}"
    );

    // Assert: package directory for context7 was removed.
    assert!(
        !context7_dir.exists(),
        "package dir for context7 should have been removed"
    );

    // Assert: lockfile no longer contains context7.
    let lock_content = fs::read_to_string(project_dir.path().join("chord.lock")).unwrap();
    assert!(
        !lock_content.contains("context7"),
        "lockfile should not contain context7, got:\n{lock_content}"
    );
    assert!(
        lock_content.contains("chrome-devtools"),
        "lockfile should still contain chrome-devtools, got:\n{lock_content}"
    );
}

#[test]
fn remove_restores_chord_toml_when_mcp_json_write_fails() {
    use chord::operations::{remove, OpContext, OperationError};

    let project = TempDir::new().unwrap();
    let packages = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();

    let original_toml = "[mcp]\ncontext7 = \"latest\"\n";
    fs::write(project.path().join("chord.toml"), original_toml).unwrap();

    // Make .mcp.json a directory (not a file) so writing it fails.
    // Easiest reproducible failure mode without OS-specific permissions.
    fs::create_dir_all(project.path().join(".mcp.json")).unwrap();

    let ctx = OpContext {
        project_root: project.path(),
        home_dir: home.path(),
        packages_dir: packages.path(),
        verbose: false,
    };

    let err = remove::remove("context7", &ctx).unwrap_err();
    assert!(matches!(err, OperationError::McpConfig(_)));

    // chord.toml restored to its pre-attempt state.
    let restored = fs::read_to_string(project.path().join("chord.toml")).unwrap();
    assert_eq!(restored, original_toml);
}

#[test]
fn remove_nonexistent_tool_exits_with_error() {
    let project_dir = TempDir::new().unwrap();
    let packages_dir = TempDir::new().unwrap();

    // Write a config without the tool we're trying to remove.
    fs::write(
        project_dir.path().join("chord.toml"),
        "[mcp]\ncontext7 = \"latest\"\n",
    )
    .unwrap();

    let mut cmd = Command::cargo_bin("chord").unwrap();
    cmd.arg("remove")
        .arg("nonexistent-tool")
        .current_dir(project_dir.path())
        .env("CHORD_HOME", packages_dir.path());

    cmd.assert().failure();
}
