use std::collections::BTreeMap;
use std::path::Path;

use serde::de::Error as _;
use serde::{Deserialize, Serialize};

/// A single locked tool entry within a lockfile section.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LockedTool {
    /// The resolved npm package name (if different from the section key).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub package: Option<String>,

    /// The exact version that was installed.
    pub version: String,

    /// Content integrity hash (e.g. `sha512-...`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub integrity: Option<String>,

    /// ISO-8601 timestamp of when the tool was resolved.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<String>,
}

/// In-memory representation of `claude-env.lock`.
///
/// The file is TOML with one table per tool type (`[mcp]`, `[skills]`, …).
/// Each table maps tool names to [`LockedTool`] entries.
///
/// Sections and entries within sections are kept sorted (via [`BTreeMap`]) so
/// that serialization is deterministic.
#[derive(Debug, Default)]
pub struct Lockfile {
    sections: BTreeMap<String, BTreeMap<String, LockedTool>>,
}

// ---------------------------------------------------------------------------
// TOML intermediate representation
// ---------------------------------------------------------------------------

/// Wire format: the full lockfile as a flat TOML map-of-maps so that `toml`
/// can deserialize it without a fixed schema.
type RawLockfile = BTreeMap<String, BTreeMap<String, LockedTool>>;

impl Lockfile {
    /// Create an empty lockfile.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns `true` if no entries have been stored yet.
    pub fn is_empty(&self) -> bool {
        self.sections.is_empty()
            || self.sections.values().all(|s| s.is_empty())
    }

    /// Parse a lockfile from a TOML string.
    ///
    /// An empty or whitespace-only string is treated as an empty lockfile
    /// rather than a parse error.
    pub fn parse(input: &str) -> Result<Self, toml::de::Error> {
        if input.trim().is_empty() {
            return Ok(Self::new());
        }
        let raw: RawLockfile = toml::from_str(input)?;
        Ok(Self { sections: raw })
    }

    /// Load a lockfile from `path`.
    ///
    /// If the file does not exist the method returns an empty lockfile rather
    /// than an error, making it safe to call before the lock has been written
    /// for the first time.
    pub fn from_file(path: &Path) -> Result<Self, toml::de::Error> {
        match std::fs::read_to_string(path) {
            Ok(content) => Self::parse(&content),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(Self::new()),
            Err(e) => Err(toml::de::Error::custom(e.to_string())),
        }
    }

    /// Look up a tool by `section` and `name`.
    pub fn get(&self, section: &str, name: &str) -> Option<&LockedTool> {
        self.sections.get(section)?.get(name)
    }

    /// Insert or update a tool entry identified by `section` and `name`.
    pub fn set(&mut self, section: &str, name: &str, tool: LockedTool) {
        self.sections
            .entry(section.to_string())
            .or_default()
            .insert(name.to_string(), tool);
    }

    /// Serialize the lockfile to a TOML string with a header comment.
    pub fn serialize(&self) -> String {
        let header = "# Auto-generated by claude-env. Do not edit.\n\n";
        let body = toml::to_string_pretty(&self.sections)
            .expect("BTreeMap<String, BTreeMap<String, LockedTool>> is always serializable");
        format!("{header}{body}")
    }

    /// Write the serialized lockfile to `path`, creating or replacing the file.
    pub fn write_to_file(&self, path: &Path) -> std::io::Result<()> {
        std::fs::write(path, self.serialize())
    }
}
