use chord::core::lockfile::{LockedTool, Lockfile};

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

#[test]
fn parse_lockfile() {
    let toml = r#"
[mcp]
context7 = { version = "1.2.3", package = "@upstash/context7-mcp", integrity = "sha512-abc", resolved_at = "2026-04-20T00:00:00Z" }
memory = { version = "0.5.0" }

[skills]
my-skill = { version = "latest", package = "skills.sh/owner/repo/my-skill" }
"#;

    let lock = Lockfile::parse(toml).unwrap();

    // mcp section
    let ctx7 = lock.get("mcp", "context7").expect("context7 should exist");
    assert_eq!(ctx7.version, "1.2.3");
    assert_eq!(ctx7.package.as_deref(), Some("@upstash/context7-mcp"));
    assert_eq!(ctx7.integrity.as_deref(), Some("sha512-abc"));
    assert_eq!(ctx7.resolved_at.as_deref(), Some("2026-04-20T00:00:00Z"));

    let mem = lock.get("mcp", "memory").expect("memory should exist");
    assert_eq!(mem.version, "0.5.0");
    assert!(mem.package.is_none());
    assert!(mem.integrity.is_none());
    assert!(mem.resolved_at.is_none());

    // skills section
    let skill = lock
        .get("skills", "my-skill")
        .expect("my-skill should exist");
    assert_eq!(skill.version, "latest");
    assert_eq!(
        skill.package.as_deref(),
        Some("skills.sh/owner/repo/my-skill")
    );
}

// ---------------------------------------------------------------------------
// Roundtrip
// ---------------------------------------------------------------------------

#[test]
fn serialize_lockfile_roundtrip() {
    let mut lock = Lockfile::new();

    lock.set(
        "mcp",
        "context7",
        LockedTool {
            package: Some("@upstash/context7-mcp".to_string()),
            version: "1.2.3".to_string(),
            integrity: Some("sha512-xyz".to_string()),
            resolved_at: Some("2026-04-20T12:00:00Z".to_string()),
            skills: None,
        },
    );
    lock.set(
        "skills",
        "my-skill",
        LockedTool {
            package: None,
            version: "latest".to_string(),
            integrity: None,
            resolved_at: None,
            skills: None,
        },
    );

    let serialized = lock.serialize();

    // Header must be present
    assert!(serialized.starts_with("# Auto-generated by chord. Do not edit.\n\n"));

    // Reparse and verify
    let lock2 = Lockfile::parse(&serialized).unwrap();

    let ctx7 = lock2
        .get("mcp", "context7")
        .expect("context7 should survive roundtrip");
    assert_eq!(ctx7.version, "1.2.3");
    assert_eq!(ctx7.package.as_deref(), Some("@upstash/context7-mcp"));
    assert_eq!(ctx7.integrity.as_deref(), Some("sha512-xyz"));
    assert_eq!(ctx7.resolved_at.as_deref(), Some("2026-04-20T12:00:00Z"));

    let skill = lock2
        .get("skills", "my-skill")
        .expect("my-skill should survive roundtrip");
    assert_eq!(skill.version, "latest");
    assert!(skill.package.is_none());
    assert!(skill.integrity.is_none());
    assert!(skill.resolved_at.is_none());
}

// ---------------------------------------------------------------------------
// Empty lockfile
// ---------------------------------------------------------------------------

#[test]
fn empty_lockfile_serializes_with_header_comment() {
    let lock = Lockfile::new();
    assert!(lock.is_empty());

    let serialized = lock.serialize();
    assert!(
        serialized.starts_with("# Auto-generated by chord. Do not edit.\n\n"),
        "expected header comment, got: {serialized:?}"
    );
}

// ---------------------------------------------------------------------------
// Missing file
// ---------------------------------------------------------------------------

#[test]
fn lockfile_from_missing_file_returns_empty() {
    let path = std::path::Path::new("/nonexistent/path/chord.lock");
    let lock =
        Lockfile::from_file(path).expect("missing file should return empty lockfile, not error");
    assert!(lock.is_empty());
}

// ---------------------------------------------------------------------------
// Wildcard anchor sub-list
// ---------------------------------------------------------------------------

#[test]
fn wildcard_anchor_row_roundtrips_with_skills_sublist() {
    use chord::core::lockfile::{LockedSkill, LockedTool, Lockfile};
    let mut lf = Lockfile::new();
    lf.set(
        "skills",
        "mattpocock/skills",
        LockedTool {
            package: None,
            version: "abc123".to_string(),
            integrity: None,
            resolved_at: Some("2026-06-25".to_string()),
            skills: Some(vec![
                LockedSkill { name: "foo".to_string(), integrity: "sha256:11".to_string() },
                LockedSkill { name: "bar".to_string(), integrity: "sha256:22".to_string() },
            ]),
        },
    );
    let serialized = lf.serialize();
    let parsed = Lockfile::parse(&serialized).unwrap();
    let row = parsed.get("skills", "mattpocock/skills").unwrap();
    assert_eq!(row.version, "abc123");
    let subs = row.skills.as_ref().unwrap();
    assert_eq!(subs.len(), 2);
    assert_eq!(subs[0].name, "foo");
}

#[test]
fn remove_prefix_drops_entry_and_descendants_only() {
    use chord::core::lockfile::{LockedTool, Lockfile};
    let mk = |v: &str| LockedTool {
        package: None, version: v.to_string(), integrity: None, resolved_at: None, skills: None,
    };
    let mut lf = Lockfile::new();
    lf.set("skills", "o/r", mk("1"));
    lf.set("skills", "o/r/foo", mk("1"));
    lf.set("skills", "o/repo2/x", mk("1"));
    lf.remove_prefix("skills", "o/r");
    assert!(lf.get("skills", "o/r").is_none());
    assert!(lf.get("skills", "o/r/foo").is_none());
    assert!(lf.get("skills", "o/repo2/x").is_some(), "sibling repo must survive");
}
