use chord::core::config::Config;
use chord::core::lockfile::{LockedTool, Lockfile};
use chord::core::store::file::{FileConfigStore, FileLockfileStore};
use chord::core::store::memory::{InMemoryConfigStore, InMemoryLockfileStore};
use chord::core::store::{ConfigStore, LockfileStore};
use std::fs;
use tempfile::TempDir;

// ── FileConfigStore ────────────────────────────────────────────────────────

#[test]
fn file_config_store_load_missing_returns_default() {
    let project = TempDir::new().unwrap();
    let store = FileConfigStore::new(project.path());

    let config = store.load().unwrap();
    assert_eq!(config, Config::default());
}

#[test]
fn file_config_store_save_then_load_roundtrips() {
    let project = TempDir::new().unwrap();
    let store = FileConfigStore::new(project.path());

    let mut config = Config::default();
    config
        .mcp
        .insert("context7".to_string(), "latest".to_string());
    store.save(&config).unwrap();

    let loaded = store.load().unwrap();
    assert_eq!(
        loaded.mcp.get("context7").map(String::as_str),
        Some("latest")
    );
}

#[test]
fn file_config_store_snapshot_preserves_exact_bytes() {
    let project = TempDir::new().unwrap();
    let original_toml = "# user comment\n[mcp]\ncontext7 = \"latest\"\n";
    fs::write(project.path().join("chord.toml"), original_toml).unwrap();

    let store = FileConfigStore::new(project.path());
    let snap = store.snapshot().unwrap();
    assert_eq!(snap, original_toml.as_bytes());

    // Overwrite with a canonicalised form, then restore.
    let mut config = store.load().unwrap();
    config.mcp.insert("memory".to_string(), "1.0.0".to_string());
    store.save(&config).unwrap();
    assert_ne!(
        fs::read(project.path().join("chord.toml")).unwrap(),
        original_toml.as_bytes()
    );

    store.restore(&snap).unwrap();
    assert_eq!(
        fs::read(project.path().join("chord.toml")).unwrap(),
        original_toml.as_bytes()
    );
}

#[test]
fn file_config_store_snapshot_of_missing_file_is_empty() {
    let project = TempDir::new().unwrap();
    let store = FileConfigStore::new(project.path());

    let snap = store.snapshot().unwrap();
    assert!(snap.is_empty());
}

// ── InMemoryConfigStore ────────────────────────────────────────────────────

#[test]
fn memory_config_store_save_then_load_roundtrips() {
    let store = InMemoryConfigStore::empty();
    let mut config = Config::default();
    config.cli.insert("bmad".to_string(), "6.1.0".to_string());
    store.save(&config).unwrap();

    let loaded = store.load().unwrap();
    assert_eq!(loaded.cli.get("bmad").map(String::as_str), Some("6.1.0"));
}

#[test]
fn memory_config_store_snapshot_restore_is_logically_equivalent() {
    let store = InMemoryConfigStore::empty();
    let mut config_a = Config::default();
    config_a
        .skills
        .insert("mattpocock/skills".to_string(), "latest".to_string());
    store.save(&config_a).unwrap();

    let snap = store.snapshot().unwrap();

    let mut config_b = config_a.clone();
    config_b
        .plugins
        .insert("foo/bar/baz@m".to_string(), "latest".to_string());
    store.save(&config_b).unwrap();
    assert_ne!(store.load().unwrap(), config_a);

    store.restore(&snap).unwrap();
    assert_eq!(store.load().unwrap(), config_a);
}

// ── FileLockfileStore ──────────────────────────────────────────────────────

#[test]
fn file_lockfile_store_load_missing_returns_empty() {
    let project = TempDir::new().unwrap();
    let store = FileLockfileStore::new(project.path());

    let lockfile = store.load().unwrap();
    assert!(lockfile.is_empty());
}

#[test]
fn file_lockfile_store_save_then_load_roundtrips() {
    let project = TempDir::new().unwrap();
    let store = FileLockfileStore::new(project.path());

    let mut lockfile = Lockfile::new();
    lockfile.set(
        "mcp",
        "context7",
        LockedTool {
            package: Some("@upstash/context7-mcp".to_string()),
            version: "2.1.4".to_string(),
            integrity: None,
            resolved_at: None,
            skills: None,
        },
    );
    store.save(&lockfile).unwrap();

    let loaded = store.load().unwrap();
    let entry = loaded.get("mcp", "context7").unwrap();
    assert_eq!(entry.version, "2.1.4");
}

#[test]
fn file_lockfile_store_snapshot_preserves_exact_bytes() {
    let project = TempDir::new().unwrap();
    let original =
        "# Auto-generated by chord. Do not edit.\n\n[mcp.context7]\nversion = \"2.1.4\"\n";
    fs::write(project.path().join("chord.lock"), original).unwrap();

    let store = FileLockfileStore::new(project.path());
    let snap = store.snapshot().unwrap();

    let mut lockfile = store.load().unwrap();
    lockfile.set(
        "mcp",
        "memory",
        LockedTool {
            package: Some("memory".to_string()),
            version: "1.0.0".to_string(),
            integrity: None,
            resolved_at: None,
            skills: None,
        },
    );
    store.save(&lockfile).unwrap();
    assert_ne!(
        fs::read(project.path().join("chord.lock")).unwrap(),
        original.as_bytes()
    );

    store.restore(&snap).unwrap();
    assert_eq!(
        fs::read(project.path().join("chord.lock")).unwrap(),
        original.as_bytes()
    );
}

// ── InMemoryLockfileStore ──────────────────────────────────────────────────

#[test]
fn memory_lockfile_store_save_then_load_roundtrips() {
    let store = InMemoryLockfileStore::empty();
    let mut lockfile = Lockfile::new();
    lockfile.set(
        "cli",
        "openspec",
        LockedTool {
            package: Some("@fission-ai/openspec".to_string()),
            version: "1.2.0".to_string(),
            integrity: None,
            resolved_at: None,
            skills: None,
        },
    );
    store.save(&lockfile).unwrap();

    let loaded = store.load().unwrap();
    let entry = loaded.get("cli", "openspec").unwrap();
    assert_eq!(entry.version, "1.2.0");
}

#[test]
fn memory_lockfile_store_snapshot_restore_is_logically_equivalent() {
    let store = InMemoryLockfileStore::empty();
    let mut lockfile_a = Lockfile::new();
    lockfile_a.set(
        "mcp",
        "context7",
        LockedTool {
            package: None,
            version: "1".to_string(),
            integrity: None,
            resolved_at: None,
            skills: None,
        },
    );
    store.save(&lockfile_a).unwrap();

    let snap = store.snapshot().unwrap();

    store.save(&Lockfile::new()).unwrap();
    assert!(store.load().unwrap().is_empty());

    store.restore(&snap).unwrap();
    let restored = store.load().unwrap();
    assert_eq!(
        restored.get("mcp", "context7").map(|t| t.version.as_str()),
        Some("1")
    );
}
